//! SVG chart drawing primitives for embedding in HTML reports.
//!
//! Functions defined here are **pure string generators**: they have no
//! external crate dependencies and perform no statistical/aggregation
//! analysis whatsoever (the caller, `builder.rs`, is assumed to already
//! pass in a computed data series). All colors are referenced via CSS
//! custom properties defined by [`super::theme`] (`var(--foo)`), and no raw
//! hex color codes are ever emitted inside the SVG (so light/dark themes
//! are followed automatically).
//!
//! # Shared conventions
//!
//! - Sizing is `viewBox`-based, and `width="100%"` makes the chart
//!   responsive (it scales to follow the page width).
//! - Ticks are determined by the 1/2/5 × 10^n "nice number" algorithm
//!   ([`nice_ticks`]).
//! - Grid lines are hairlines (1px, `var(--grid)`); axis labels use muted
//!   ink (`var(--ink-muted)`).
//! - Every data mark gets a `<title>` child element so it works as a
//!   browser-native tooltip (this supports the no-JS design policy).
//! - `<text>` elements specify `font-family="inherit"` so no font name is
//!   embedded in the SVG (the font is inherited from the host HTML page's
//!   CSS). Numeric labels get `font-variant-numeric: tabular-nums`.
//! - Charts with only a single series omit the legend (the `<title>`
//!   doubles as the series name).
//! - Drawing elements are written directly into the output buffer via
//!   `write!` ([`std::fmt::Write`]), avoiding a disposable `String`
//!   allocation per element.

use std::fmt::Write as _;

use super::theme;

// ================================================================
// Shared infrastructure
// ================================================================

/// Font size shared by all text (in viewBox units).
///
/// Without an explicit value on the SVG side, text renders at the page's
/// default size (around 16px), which breaks character-width-based margin
/// calculations, so this value is always emitted as the `font-size`
/// attribute (the font **family** stays `inherit` and follows the page).
const FONT_SIZE: f64 = 12.0;

/// Estimated width per character used for margin calculations (px, at
/// `FONT_SIZE`).
///
/// Set a bit wider than the average alphanumeric character width for
/// system-ui-style fonts, as a safety margin so truncated labels don't
/// overflow the margin.
const CHAR_W: f64 = 7.0;

/// Padding around the plot area. Determined by whether labels are present.
struct Margins {
    top: f64,
    right: f64,
    bottom: f64,
    left: f64,
}

/// Escapes a string so it is safe as XML text content / attribute value.
///
/// The order of operations matters: `&` must be processed first, otherwise
/// the entity references generated by later substitutions (e.g. `&amp;`)
/// would get double-escaped.
///
/// The escaped set (`& < > " '`) is also safe for HTML text nodes /
/// double-quoted attribute values, and the `html` renderer shares this
/// implementation (`&apos;` is a valid entity reference in HTML5, so this
/// isn't a discrepancy).
pub(crate) fn escape_xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

/// Numeric formatter for SVG coordinates/sizes (fixed to 2 decimal places).
///
/// Serves a different purpose than the formatter used to display data
/// values ([`fmt_sig4`]) — this one is for drawing coordinates and has no
/// notion of significant digits.
fn coord(v: f64) -> String {
    format!("{v:.2}")
}

/// 4-significant-digit formatter for displaying data values (equivalent to
/// `%.4g`).
///
/// This intentionally duplicates the shared formatter used elsewhere in
/// the report (presumably `crate::report::format_number`), in order to
/// keep `report::svg` loosely coupled from other modules (see the design
/// doc).
fn fmt_sig4(v: f64) -> String {
    if v == 0.0 {
        return "0".to_string();
    }
    if v.is_nan() {
        return "NaN".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 {
            "inf".to_string()
        } else {
            "-inf".to_string()
        };
    }

    let sign = if v.is_sign_negative() { "-" } else { "" };
    let av = v.abs();
    let exponent = av.log10().floor() as i32;

    if !(-4..4).contains(&exponent) {
        // Exponential notation: round the mantissa to 4 significant digits
        // (3 decimal places).
        let mantissa = av / 10f64.powi(exponent);
        let mantissa_str = trim_trailing_zeros(&format!("{mantissa:.3}"));
        let exp_sign = if exponent >= 0 { "+" } else { "-" };
        format!("{sign}{mantissa_str}e{exp_sign}{}", exponent.abs())
    } else {
        let decimals = (3 - exponent).max(0) as usize;
        let s = trim_trailing_zeros(&format!("{av:.decimals$}"));
        format!("{sign}{s}")
    }
}

/// Strips trailing zeros after the decimal point (and any now-unneeded
/// decimal point).
fn trim_trailing_zeros(s: &str) -> String {
    if !s.contains('.') {
        return s.to_string();
    }
    let trimmed = s.trim_end_matches('0');
    trimmed.trim_end_matches('.').to_string()
}

/// Computes a nice number (1 / 2 / 5 × 10^n).
///
/// If `round` is true, returns the nearest nice number; if false, returns
/// the smallest nice number that is `>= range` (used to determine tick
/// spacing).
fn nice_num(range: f64, round: bool) -> f64 {
    if range <= 0.0 {
        return 1.0;
    }
    let exponent = range.log10().floor();
    let fraction = range / 10f64.powf(exponent);
    let nice_fraction = if round {
        if fraction < 1.5 {
            1.0
        } else if fraction < 3.0 {
            2.0
        } else if fraction < 7.0 {
            5.0
        } else {
            10.0
        }
    } else if fraction <= 1.0 {
        1.0
    } else if fraction <= 2.0 {
        2.0
    } else if fraction <= 5.0 {
        5.0
    } else {
        10.0
    };
    nice_fraction * 10f64.powf(exponent)
}

/// Computes tick positions using the nice-number algorithm (Heckbert's
/// method).
///
/// In the degenerate case `min == max`, an artificial width is applied
/// around the value before the usual algorithm runs (`[-1, 1]` if
/// `min == max == 0.0`, otherwise half the absolute value as the width),
/// so single-point data or constant series never panic or produce NaN and
/// always return at least two ticks.
fn nice_ticks(min: f64, max: f64, target_count: usize) -> Vec<f64> {
    let (min, max) = if min > max { (max, min) } else { (min, max) };
    let (min, max) = if (max - min).abs() < f64::EPSILON {
        let pad = if min == 0.0 { 1.0 } else { min.abs() * 0.5 };
        (min - pad, max + pad)
    } else {
        (min, max)
    };

    let target = target_count.max(2);
    let range = nice_num(max - min, false);
    let spacing = nice_num(range / (target - 1) as f64, true);
    let nice_min = (min / spacing).floor() * spacing;
    let nice_max = (max / spacing).ceil() * spacing;

    let n = ((nice_max - nice_min) / spacing).round() as i64;
    (0..=n).map(|i| nice_min + spacing * i as f64).collect()
}

/// Computes integer ticks (for the trial-number X axis).
///
/// Rounds the [`nice_ticks`] result and removes duplicates; if fewer than
/// two ticks remain, falls back to the actual min/max values (as
/// integers).
fn nice_ticks_integer(min: f64, max: f64, target_count: usize) -> Vec<i64> {
    let mut ticks: Vec<i64> = nice_ticks(min, max, target_count)
        .into_iter()
        .map(|t| t.round() as i64)
        .collect();
    ticks.dedup();
    if ticks.len() >= 2 {
        return ticks;
    }
    let lo = min.floor() as i64;
    let hi = max.ceil() as i64;
    if lo == hi {
        vec![lo]
    } else {
        vec![lo, hi]
    }
}

/// Writes a hairline grid line (`<line>`) to `body`.
fn hairline(body: &mut String, x1: f64, y1: f64, x2: f64, y2: f64) {
    let _ = writeln!(
        body,
        "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"var({grid})\" stroke-width=\"1\" />",
        coord(x1),
        coord(y1),
        coord(x2),
        coord(y2),
        grid = theme::VAR_GRID
    );
}

/// Writes an axis line (`<line>`) to `body`.
fn axis_line(body: &mut String, x1: f64, y1: f64, x2: f64, y2: f64) {
    let _ = writeln!(
        body,
        "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"var({axis})\" stroke-width=\"1\" />",
        coord(x1),
        coord(y1),
        coord(x2),
        coord(y2),
        axis = theme::VAR_AXIS
    );
}

/// Writes muted-ink text (for axis ticks / category labels) to `body`.
fn text_muted(body: &mut String, x: f64, y: f64, anchor: &str, content: &str, numeric: bool) {
    let style = if numeric {
        " style=\"font-variant-numeric: tabular-nums\""
    } else {
        ""
    };
    let _ = writeln!(
        body,
        "<text x=\"{}\" y=\"{}\" text-anchor=\"{anchor}\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\"{style}>{}</text>",
        coord(x),
        coord(y),
        escape_xml(content),
        fs = FONT_SIZE,
        muted = theme::VAR_INK_MUTED
    );
}

/// Writes a secondary-ink direct data label (final value, bar-end value,
/// etc.) to `body`.
fn text_secondary(body: &mut String, x: f64, y: f64, anchor: &str, content: &str) {
    let _ = writeln!(
        body,
        "<text x=\"{}\" y=\"{}\" text-anchor=\"{anchor}\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({secondary})\" style=\"font-variant-numeric: tabular-nums\">{}</text>",
        coord(x),
        coord(y),
        escape_xml(content),
        fs = FONT_SIZE,
        secondary = theme::VAR_INK_SECONDARY
    );
}

/// Wraps the chart body in the SVG root element (viewBox-based, responsive).
fn svg_wrap(width: f64, height: f64, body: &str) -> String {
    format!(
        "<svg viewBox=\"0 0 {w} {h}\" width=\"100%\" height=\"auto\" preserveAspectRatio=\"xMinYMin meet\" xmlns=\"http://www.w3.org/2000/svg\">\n{body}</svg>\n",
        w = coord(width),
        h = coord(height)
    )
}

/// Placeholder shown when the data is empty.
fn empty_message(width: f64, height: f64) -> String {
    let mut body = String::new();
    text_muted(
        &mut body,
        width / 2.0,
        height / 2.0,
        "middle",
        "no data",
        false,
    );
    svg_wrap(width, height, &body)
}

/// Truncates a category label to the given character count, appending `…`
/// if it was too long.
fn truncate_label(s: &str, max_chars: usize) -> String {
    let chars: Vec<char> = s.chars().collect();
    if chars.len() <= max_chars {
        s.to_string()
    } else {
        let head: String = chars[..max_chars.saturating_sub(1)].iter().collect();
        format!("{head}…")
    }
}

// ================================================================
// line_chart (best-so-far / HV history)
// ================================================================

/// One point of a [`line_chart`]. X = trial number, Y = value.
#[derive(Debug, Clone, Copy)]
pub struct LinePoint {
    /// Trial number.
    pub trial_number: i64,
    /// Value (best-so-far or HV).
    pub value: f64,
}

/// Draws a line chart of the convergence curve (best-so-far / HV history).
///
/// Single series, no fill, 2px stroke. `improvement_marks` is a set of
/// indices into `points`; only best-update points get a 4px marker (the
/// caller passes in the already-determined values — this function does
/// not judge that itself). The final point always shows a direct label
/// (its value); if the final point is not in `improvement_marks`, a
/// marker is added for it too. The X axis uses integer (trial-number)
/// ticks.
pub fn line_chart(
    points: &[LinePoint],
    improvement_marks: &[usize],
    width: f64,
    height: f64,
) -> String {
    if points.is_empty() {
        return empty_message(width, height);
    }

    let x_min = points[0].trial_number as f64;
    let x_max = points[points.len() - 1].trial_number as f64;
    let y_min_raw = points.iter().map(|p| p.value).fold(f64::INFINITY, f64::min);
    let y_max_raw = points
        .iter()
        .map(|p| p.value)
        .fold(f64::NEG_INFINITY, f64::max);

    let y_ticks = nice_ticks(y_min_raw, y_max_raw, 5);
    let y_min = y_ticks[0];
    let y_max = y_ticks[y_ticks.len() - 1];
    let x_ticks = nice_ticks_integer(x_min, x_max, 6);

    let last_idx = points.len() - 1;
    let final_label = fmt_sig4(points[last_idx].value);

    let max_y_tick_chars = y_ticks
        .iter()
        .map(|t| fmt_sig4(*t).chars().count())
        .max()
        .unwrap_or(1);
    let m = Margins {
        top: 14.0,
        right: 20.0 + final_label.chars().count() as f64 * CHAR_W,
        bottom: 30.0,
        left: 16.0 + max_y_tick_chars as f64 * CHAR_W,
    };
    let plot_w = (width - m.left - m.right).max(1.0);
    let plot_h = (height - m.top - m.bottom).max(1.0);

    let sx = |tn: f64| -> f64 {
        if (x_max - x_min).abs() < f64::EPSILON {
            m.left + plot_w / 2.0
        } else {
            m.left + (tn - x_min) / (x_max - x_min) * plot_w
        }
    };
    let sy = |v: f64| -> f64 {
        if (y_max - y_min).abs() < f64::EPSILON {
            m.top + plot_h / 2.0
        } else {
            m.top + plot_h - (v - y_min) / (y_max - y_min) * plot_h
        }
    };

    let mut body = String::new();

    for t in &y_ticks {
        let y = sy(*t);
        hairline(&mut body, m.left, y, m.left + plot_w, y);
        text_muted(&mut body, m.left - 8.0, y + 3.0, "end", &fmt_sig4(*t), true);
    }
    axis_line(
        &mut body,
        m.left,
        m.top + plot_h,
        m.left + plot_w,
        m.top + plot_h,
    );
    for t in &x_ticks {
        let x = sx(*t as f64);
        text_muted(
            &mut body,
            x,
            m.top + plot_h + 18.0,
            "middle",
            &t.to_string(),
            true,
        );
    }

    let path_points = points
        .iter()
        .map(|p| {
            format!(
                "{},{}",
                coord(sx(p.trial_number as f64)),
                coord(sy(p.value))
            )
        })
        .collect::<Vec<_>>()
        .join(" ");
    let _ = writeln!(
        body,
        "<polyline points=\"{path_points}\" fill=\"none\" stroke=\"var({series1})\" stroke-width=\"2\" />",
        series1 = theme::VAR_SERIES[0]
    );

    let marker = |idx: usize, body: &mut String| {
        let p = &points[idx];
        let cx = sx(p.trial_number as f64);
        let cy = sy(p.value);
        let title = escape_xml(&format!(
            "trial #{} = {}",
            p.trial_number,
            fmt_sig4(p.value)
        ));
        let _ = writeln!(
            body,
            "<circle cx=\"{}\" cy=\"{}\" r=\"4\" fill=\"var({series1})\"><title>{title}</title></circle>",
            coord(cx),
            coord(cy),
            series1 = theme::VAR_SERIES[0]
        );
    };

    for &idx in improvement_marks {
        if idx < points.len() {
            marker(idx, &mut body);
        }
    }
    if !improvement_marks.contains(&last_idx) {
        marker(last_idx, &mut body);
    }

    let last = &points[last_idx];
    text_secondary(
        &mut body,
        sx(last.trial_number as f64) + 8.0,
        sy(last.value) + 4.0,
        "start",
        &final_label,
    );

    svg_wrap(width, height, &body)
}

// ================================================================
// scatter_chart (Pareto front)
// ================================================================

/// One point of a [`scatter_chart`].
#[derive(Debug, Clone, Copy)]
pub struct ScatterPoint {
    /// Trial number (shown in tooltip).
    pub trial_number: i64,
    /// X coordinate (first objective value).
    pub x: f64,
    /// Y coordinate (second objective value).
    pub y: f64,
    /// Whether this point satisfies all constraints (always `true` for
    /// unconstrained studies). Points with `false` get `[infeasible]`
    /// appended to their tooltip.
    pub feasible: bool,
}

/// Draws a Pareto scatter plot.
///
/// `background` is all COMPLETE points (muted, semi-transparent, r=4);
/// `front` is the non-dominated points (`series-1`, r=5). `front` is
/// internally sorted by ascending X and then connected with a staircase
/// line (1.5px) — no staircase line is drawn if `front` has fewer than two
/// points. Objective names are passed in as axis labels. When both the
/// front and dominated series are present, a small legend is shown in the
/// upper-right of the plot (the rule that two or more series require a
/// legend).
pub fn scatter_chart(
    background: &[ScatterPoint],
    front: &[ScatterPoint],
    x_label: &str,
    y_label: &str,
    width: f64,
    height: f64,
) -> String {
    if background.is_empty() && front.is_empty() {
        return empty_message(width, height);
    }

    let all_x: Vec<f64> = background.iter().chain(front.iter()).map(|p| p.x).collect();
    let all_y: Vec<f64> = background.iter().chain(front.iter()).map(|p| p.y).collect();
    let x_min_raw = all_x.iter().copied().fold(f64::INFINITY, f64::min);
    let x_max_raw = all_x.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let y_min_raw = all_y.iter().copied().fold(f64::INFINITY, f64::min);
    let y_max_raw = all_y.iter().copied().fold(f64::NEG_INFINITY, f64::max);

    let x_ticks = nice_ticks(x_min_raw, x_max_raw, 5);
    let y_ticks = nice_ticks(y_min_raw, y_max_raw, 5);
    let x_min = x_ticks[0];
    let x_max = x_ticks[x_ticks.len() - 1];
    let y_min = y_ticks[0];
    let y_max = y_ticks[y_ticks.len() - 1];

    // Left margin = space for the rotated Y-axis title (16px) + max tick
    // label width + padding. Top margin reserves one line for the legend
    // (a legend is required because there are two series, front and
    // dominated; the shared rule of no legend for a single series applies
    // to the other charts).
    let max_y_tick_chars = y_ticks
        .iter()
        .map(|t| fmt_sig4(*t).chars().count())
        .max()
        .unwrap_or(1);
    let has_legend = !background.is_empty() && !front.is_empty();
    let m = Margins {
        top: if has_legend { 28.0 } else { 14.0 },
        right: 16.0,
        bottom: 44.0,
        left: 16.0 + max_y_tick_chars as f64 * CHAR_W + 12.0,
    };
    let plot_w = (width - m.left - m.right).max(1.0);
    let plot_h = (height - m.top - m.bottom).max(1.0);

    let sx = |v: f64| -> f64 {
        if (x_max - x_min).abs() < f64::EPSILON {
            m.left + plot_w / 2.0
        } else {
            m.left + (v - x_min) / (x_max - x_min) * plot_w
        }
    };
    let sy = |v: f64| -> f64 {
        if (y_max - y_min).abs() < f64::EPSILON {
            m.top + plot_h / 2.0
        } else {
            m.top + plot_h - (v - y_min) / (y_max - y_min) * plot_h
        }
    };

    let mut body = String::new();

    scatter_frame(
        &mut body, &m, plot_w, plot_h, height, &x_ticks, &y_ticks, &sx, &sy, x_label, y_label,
    );
    scatter_points(&mut body, background, front, &sx, &sy);
    if has_legend {
        scatter_legend(&mut body, &m, plot_w);
    }

    svg_wrap(width, height, &body)
}

/// Writes the scatter plot's frame (grid lines, tick labels, axis lines,
/// axis titles).
#[allow(clippy::too_many_arguments)]
fn scatter_frame(
    body: &mut String,
    m: &Margins,
    plot_w: f64,
    plot_h: f64,
    height: f64,
    x_ticks: &[f64],
    y_ticks: &[f64],
    sx: &dyn Fn(f64) -> f64,
    sy: &dyn Fn(f64) -> f64,
    x_label: &str,
    y_label: &str,
) {
    for t in y_ticks {
        let y = sy(*t);
        hairline(body, m.left, y, m.left + plot_w, y);
        text_muted(body, m.left - 8.0, y + 3.0, "end", &fmt_sig4(*t), true);
    }
    for t in x_ticks {
        let x = sx(*t);
        hairline(body, x, m.top, x, m.top + plot_h);
        text_muted(
            body,
            x,
            m.top + plot_h + 18.0,
            "middle",
            &fmt_sig4(*t),
            true,
        );
    }
    axis_line(
        body,
        m.left,
        m.top + plot_h,
        m.left + plot_w,
        m.top + plot_h,
    );
    axis_line(body, m.left, m.top, m.left, m.top + plot_h);

    text_muted(
        body,
        m.left + plot_w / 2.0,
        height - 4.0,
        "middle",
        x_label,
        false,
    );
    // Y-axis title: placed vertically with rotate(-90) inside the left
    // margin (further left than the tick labels). Rotation center =
    // (14, vertical center of the plot).
    let ty = m.top + plot_h / 2.0;
    let _ = writeln!(
        body,
        "<text x=\"14\" y=\"{}\" transform=\"rotate(-90 14 {})\" text-anchor=\"middle\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\">{}</text>",
        coord(ty),
        coord(ty),
        escape_xml(y_label),
        fs = FONT_SIZE,
        muted = theme::VAR_INK_MUTED
    );
}

/// Writes the scatter plot's data marks (background points, front
/// staircase line, front points).
fn scatter_points(
    body: &mut String,
    background: &[ScatterPoint],
    front: &[ScatterPoint],
    sx: &dyn Fn(f64) -> f64,
    sy: &dyn Fn(f64) -> f64,
) {
    for p in background {
        let title = escape_xml(&scatter_title(p, false));
        let _ = writeln!(
            body,
            "<circle cx=\"{}\" cy=\"{}\" r=\"4\" fill=\"var({muted})\" fill-opacity=\"0.4\"><title>{title}</title></circle>",
            coord(sx(p.x)),
            coord(sy(p.y)),
            muted = theme::VAR_INK_MUTED
        );
    }

    if front.len() >= 2 {
        let mut sorted_front: Vec<&ScatterPoint> = front.iter().collect();
        sorted_front.sort_by(|a, b| a.x.partial_cmp(&b.x).unwrap_or(std::cmp::Ordering::Equal));
        let mut path = format!(
            "M {} {}",
            coord(sx(sorted_front[0].x)),
            coord(sy(sorted_front[0].y))
        );
        for w in sorted_front.windows(2) {
            let (prev, cur) = (w[0], w[1]);
            let _ = write!(
                path,
                " L {} {} L {} {}",
                coord(sx(cur.x)),
                coord(sy(prev.y)),
                coord(sx(cur.x)),
                coord(sy(cur.y))
            );
        }
        let _ = writeln!(
            body,
            "<path d=\"{path}\" fill=\"none\" stroke=\"var({series1})\" stroke-width=\"1.5\" />",
            series1 = theme::VAR_SERIES[0]
        );
    }

    for p in front {
        let title = escape_xml(&scatter_title(p, true));
        let _ = writeln!(
            body,
            "<circle cx=\"{}\" cy=\"{}\" r=\"5\" fill=\"var({series1})\"><title>{title}</title></circle>",
            coord(sx(p.x)),
            coord(sy(p.y)),
            series1 = theme::VAR_SERIES[0]
        );
    }
}

/// Tooltip string for a scatter point (including front / infeasible
/// annotations).
fn scatter_title(p: &ScatterPoint, on_front: bool) -> String {
    let mut title = format!(
        "trial #{} ({}, {})",
        p.trial_number,
        fmt_sig4(p.x),
        fmt_sig4(p.y)
    );
    if on_front {
        title.push_str(" [front]");
    }
    if !p.feasible {
        title.push_str(" [infeasible]");
    }
    title
}

/// Legend (only when both the front and dominated series are present):
/// places "● Pareto front ● dominated" right-aligned inside the top
/// margin at the upper-right of the plot. Legend markers are not data
/// marks, so they get no `<title>`.
fn scatter_legend(body: &mut String, m: &Margins, plot_w: f64) {
    const LEGEND_FRONT: &str = "Pareto front";
    const LEGEND_BG: &str = "dominated";
    let w_front = LEGEND_FRONT.chars().count() as f64 * CHAR_W;
    let w_bg = LEGEND_BG.chars().count() as f64 * CHAR_W;
    let item_gap = 18.0;
    let marker_w = 12.0; // marker diameter + gap to text
    let total = marker_w + w_front + item_gap + marker_w + w_bg;
    let start_x = (m.left + plot_w - total).max(m.left);
    let cy = 10.0;
    let text_y = cy + 4.0;

    let _ = writeln!(
        body,
        "<circle cx=\"{}\" cy=\"{}\" r=\"4\" fill=\"var({series1})\" />",
        coord(start_x + 4.0),
        coord(cy),
        series1 = theme::VAR_SERIES[0]
    );
    text_muted(
        body,
        start_x + marker_w,
        text_y,
        "start",
        LEGEND_FRONT,
        false,
    );
    let x2 = start_x + marker_w + w_front + item_gap;
    let _ = writeln!(
        body,
        "<circle cx=\"{}\" cy=\"{}\" r=\"4\" fill=\"var({muted})\" fill-opacity=\"0.4\" />",
        coord(x2 + 4.0),
        coord(cy),
        muted = theme::VAR_INK_MUTED
    );
    text_muted(body, x2 + marker_w, text_y, "start", LEGEND_BG, false);
}

// ================================================================
// hbar_chart (parameter importance)
// ================================================================

/// One bar of an [`hbar_chart`].
#[derive(Debug, Clone)]
pub struct HBarItem {
    /// Category name (e.g. parameter name).
    pub label: String,
    /// Value (importance score).
    pub value: f64,
}

/// Draws a horizontal bar chart (height auto-determined from item count).
///
/// Bars use a single `series-1` color (ranking is not color-coded). Bar
/// height 20px, rounded corners `rx=2`, 8px gap between bars. The value is
/// labeled directly at the right end of the bar, and the category name is
/// shown on the left (truncated with `…` beyond 24 characters, with the
/// full label preserved in `<title>`).
pub fn hbar_chart(items: &[HBarItem], width: f64) -> String {
    const BAR_H: f64 = 20.0;
    const GAP: f64 = 8.0;
    const MAX_LABEL_CHARS: usize = 24;

    if items.is_empty() {
        return empty_message(width, 40.0);
    }

    let n = items.len();
    let top = 8.0;
    let bottom = 24.0;
    let height = top + bottom + n as f64 * BAR_H + (n.saturating_sub(1)) as f64 * GAP;

    let max_val = items
        .iter()
        .map(|it| it.value)
        .fold(f64::NEG_INFINITY, f64::max)
        .max(0.0);
    let value_ticks = nice_ticks(0.0, max_val, 4);
    let x_max = value_ticks[value_ticks.len() - 1].max(f64::EPSILON);

    let max_label_len = items
        .iter()
        .map(|it| truncate_label(&it.label, MAX_LABEL_CHARS).chars().count())
        .max()
        .unwrap_or(0);
    let max_value_len = items
        .iter()
        .map(|it| fmt_sig4(it.value).chars().count())
        .max()
        .unwrap_or(1);

    // The left margin is dynamically sized as
    // max display label chars (after truncation) × CHAR_W + padding
    // (since labels are placed at m.left - 8 with an end anchor, we need
    // the full label width + anchor padding + left-edge padding).
    let m = Margins {
        top,
        right: 16.0 + max_value_len as f64 * CHAR_W,
        bottom,
        left: 12.0 + max_label_len as f64 * CHAR_W + 8.0,
    };
    let plot_w = (width - m.left - m.right).max(1.0);

    let mut body = String::new();

    for t in &value_ticks {
        let x = m.left + (t / x_max) * plot_w;
        hairline(&mut body, x, m.top, x, height - m.bottom);
        text_muted(
            &mut body,
            x,
            height - m.bottom + 16.0,
            "middle",
            &fmt_sig4(*t),
            true,
        );
    }

    for (i, item) in items.iter().enumerate() {
        let y_top = m.top + i as f64 * (BAR_H + GAP);
        let y_mid = y_top + BAR_H / 2.0 + 4.0;
        let bar_w = ((item.value.max(0.0) / x_max) * plot_w).max(0.0);

        let full_label_escaped = escape_xml(&item.label);
        let display_label = truncate_label(&item.label, MAX_LABEL_CHARS);
        let _ = writeln!(
            body,
            "<text x=\"{}\" y=\"{}\" text-anchor=\"end\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\"><title>{full_label_escaped}</title>{}</text>",
            coord(m.left - 8.0),
            coord(y_mid),
            escape_xml(&display_label),
            fs = FONT_SIZE,
            muted = theme::VAR_INK_MUTED
        );

        let title = escape_xml(&format!("{}: {}", item.label, fmt_sig4(item.value)));
        let _ = writeln!(
            body,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" rx=\"2\" fill=\"var({series1})\"><title>{title}</title></rect>",
            coord(m.left),
            coord(y_top),
            coord(bar_w),
            coord(BAR_H),
            series1 = theme::VAR_SERIES[0]
        );

        text_secondary(
            &mut body,
            m.left + bar_w + 6.0,
            y_mid,
            "start",
            &fmt_sig4(item.value),
        );
    }

    svg_wrap(width, height, &body)
}

// ================================================================
// histogram (objective value distribution)
// ================================================================

/// One bin of a [`histogram`].
#[derive(Debug, Clone, Copy)]
pub struct HistBin {
    /// Lower bin edge.
    pub lower: f64,
    /// Upper bin edge.
    pub upper: f64,
    /// Count.
    pub count: u64,
}

/// Draws a histogram (single sequential color, 2px gap between bins).
pub fn histogram(bins: &[HistBin], width: f64, height: f64) -> String {
    const GAP: f64 = 2.0;

    if bins.is_empty() {
        return empty_message(width, height);
    }

    let max_count = bins.iter().map(|b| b.count).max().unwrap_or(0);
    let y_ticks = nice_ticks(0.0, max_count as f64, 4);
    let y_max = y_ticks[y_ticks.len() - 1].max(1.0);

    let max_y_tick_chars = y_ticks
        .iter()
        .map(|t| format!("{}", t.round() as i64).chars().count())
        .max()
        .unwrap_or(1);
    let m = Margins {
        top: 12.0,
        right: 12.0,
        bottom: 28.0,
        left: 16.0 + max_y_tick_chars as f64 * CHAR_W,
    };
    let plot_w = (width - m.left - m.right).max(1.0);
    let plot_h = (height - m.top - m.bottom).max(1.0);

    let n = bins.len();
    let bin_w = ((plot_w - GAP * (n.saturating_sub(1)) as f64) / n as f64).max(0.5);

    let mut body = String::new();

    for t in &y_ticks {
        let y = m.top + plot_h - (t / y_max) * plot_h;
        hairline(&mut body, m.left, y, m.left + plot_w, y);
        text_muted(
            &mut body,
            m.left - 8.0,
            y + 3.0,
            "end",
            &format!("{}", t.round() as i64),
            true,
        );
    }

    for (i, bin) in bins.iter().enumerate() {
        let x = m.left + i as f64 * (bin_w + GAP);
        let bar_h = (bin.count as f64 / y_max) * plot_h;
        let y = m.top + plot_h - bar_h;
        let title = escape_xml(&format!(
            "[{}, {}): {}",
            fmt_sig4(bin.lower),
            fmt_sig4(bin.upper),
            bin.count
        ));
        let _ = writeln!(
            body,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"var({seq400})\"><title>{title}</title></rect>",
            coord(x),
            coord(y),
            coord(bin_w),
            coord(bar_h),
            seq400 = theme::VAR_SEQ[3].1
        );
    }

    // X-axis representative ticks (first bin's lower edge / middle
    // boundary / last bin's upper edge).
    let first = bins[0].lower;
    let mid = bins[n / 2].lower;
    let last = bins[n - 1].upper;
    for (val, x) in [
        (first, m.left),
        (mid, m.left + (n / 2) as f64 * (bin_w + GAP)),
        (last, m.left + plot_w),
    ] {
        text_muted(&mut body, x, height - 8.0, "middle", &fmt_sig4(val), true);
    }

    svg_wrap(width, height, &body)
}

// ================================================================
// heatmap (correlation heatmap)
// ================================================================

/// Max display character count for row labels (excess is truncated with
/// `…` + `<title>`).
const HEATMAP_MAX_ROW_CHARS: usize = 24;
/// Max display character count for column labels. This bound keeps the
/// projected height of the rotated labels (= top margin) finite; excess
/// is truncated to `…` + `<title>`.
const HEATMAP_MAX_COL_CHARS: usize = 22;

/// Draws a correlation heatmap (diverging color scheme, value range
/// `[-1, 1]`).
///
/// Shape is `matrix[row][col]`. Cells have a 2px gap, and values are
/// quantized into a diverging 5+5+neutral scale
/// ([`theme::diverging_bin`]) for fill color; only cells with
/// `|value| > 0.5` get a direct numeric label (ink switches between
/// black/white based on cell lightness via [`theme::diverging_ink_var`]).
/// A discrete color legend showing the quantization steps is drawn on the
/// right.
///
/// Width is given by the `width` argument; height is auto-determined from
/// the row count (about 28px per row). Assumes
/// `row_labels.len() == matrix.len()` and
/// `col_labels.len() == matrix[0].len()`.
///
/// Row labels are truncated to 24 characters, column labels to 22
/// (appending `…`, with the full label kept in `<title>`); the left
/// margin is sized dynamically from the display label width, and the top
/// margin from the vertical projected height of the column labels rotated
/// by -40°.
pub fn heatmap(
    matrix: &[Vec<f64>],
    row_labels: &[String],
    col_labels: &[String],
    width: f64,
) -> String {
    const GAP: f64 = 2.0;
    const CELL_H: f64 = 28.0;
    const LEGEND_W: f64 = 90.0;
    /// Vertical projected height per character of a column label rotated
    /// by -40° (`CHAR_W × sin(40°) ≈ 7.0 × 0.643`).
    const COL_LABEL_RISE: f64 = 4.5;

    let rows = matrix.len();
    let cols = matrix.first().map(Vec::len).unwrap_or(0);
    if rows == 0 || cols == 0 {
        return empty_message(width, 40.0);
    }

    // Determine margins dynamically from the max display (post-truncation)
    // label character count.
    let max_row_chars = row_labels
        .iter()
        .map(|s| truncate_label(s, HEATMAP_MAX_ROW_CHARS).chars().count())
        .max()
        .unwrap_or(0);
    let max_col_chars = col_labels
        .iter()
        .map(|s| truncate_label(s, HEATMAP_MAX_COL_CHARS).chars().count())
        .max()
        .unwrap_or(0);
    let m = Margins {
        top: 24.0 + max_col_chars as f64 * COL_LABEL_RISE,
        right: LEGEND_W + 16.0,
        bottom: 8.0,
        left: 12.0 + max_row_chars as f64 * CHAR_W + 8.0,
    };

    let height = m.top + m.bottom + rows as f64 * CELL_H + (rows.saturating_sub(1)) as f64 * GAP;
    let plot_w = (width - m.left - m.right).max(1.0);
    let plot_h = rows as f64 * CELL_H + (rows.saturating_sub(1)) as f64 * GAP;
    let cell_w = ((plot_w - GAP * (cols.saturating_sub(1)) as f64) / cols as f64).max(0.5);

    let mut body = String::new();

    heatmap_col_labels(&mut body, col_labels, cols, &m, cell_w, GAP);
    heatmap_cells(
        &mut body, matrix, row_labels, col_labels, rows, cols, &m, cell_w, CELL_H, GAP,
    );
    heatmap_legend(&mut body, width, &m, plot_h, LEGEND_W);

    svg_wrap(width, height, &body)
}

/// Writes the heatmap's column labels (rotate(-40°), truncation +
/// `<title>` fallback).
fn heatmap_col_labels(
    body: &mut String,
    col_labels: &[String],
    cols: usize,
    m: &Margins,
    cell_w: f64,
    gap: f64,
) {
    for (c, label) in col_labels.iter().enumerate().take(cols) {
        let cx = m.left + c as f64 * (cell_w + gap) + cell_w / 2.0;
        let cy = m.top - 8.0;
        let display = truncate_label(label, HEATMAP_MAX_COL_CHARS);
        // Only keep the full label in <title> when truncation occurred.
        let title = if display == *label {
            String::new()
        } else {
            format!("<title>{}</title>", escape_xml(label))
        };
        let _ = writeln!(
            body,
            "<text x=\"{}\" y=\"{}\" transform=\"rotate(-40 {} {})\" text-anchor=\"start\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\">{title}{}</text>",
            coord(cx),
            coord(cy),
            coord(cx),
            coord(cy),
            escape_xml(&display),
            fs = FONT_SIZE,
            muted = theme::VAR_INK_MUTED
        );
    }
}

/// Writes the heatmap's row labels and cells (quantized fill + direct
/// label for highly-correlated cells).
#[allow(clippy::too_many_arguments)]
fn heatmap_cells(
    body: &mut String,
    matrix: &[Vec<f64>],
    row_labels: &[String],
    col_labels: &[String],
    rows: usize,
    cols: usize,
    m: &Margins,
    cell_w: f64,
    cell_h: f64,
    gap: f64,
) {
    for (r, row) in matrix.iter().enumerate().take(rows) {
        let y = m.top + r as f64 * (cell_h + gap);
        let row_label = row_labels.get(r).map(String::as_str).unwrap_or("");
        let display = truncate_label(row_label, HEATMAP_MAX_ROW_CHARS);
        let title = if display == row_label {
            String::new()
        } else {
            format!("<title>{}</title>", escape_xml(row_label))
        };
        let _ = writeln!(
            body,
            "<text x=\"{}\" y=\"{}\" text-anchor=\"end\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\">{title}{}</text>",
            coord(m.left - 8.0),
            coord(y + cell_h / 2.0 + 4.0),
            escape_xml(&display),
            fs = FONT_SIZE,
            muted = theme::VAR_INK_MUTED
        );

        for (c, &value) in row.iter().enumerate().take(cols) {
            let x = m.left + c as f64 * (cell_w + gap);
            let clamped = value.clamp(-1.0, 1.0);
            let bin = theme::diverging_bin(clamped);
            let fill_var = theme::diverging_var(bin);
            let col_label = col_labels.get(c).map(String::as_str).unwrap_or("");
            let title = escape_xml(&format!("{row_label} × {col_label}: {}", fmt_sig4(value)));
            let _ = writeln!(
                body,
                "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"var({fill_var})\"><title>{title}</title></rect>",
                coord(x),
                coord(y),
                coord(cell_w),
                coord(cell_h)
            );

            if theme::diverging_show_label(value) {
                let ink_var = theme::diverging_ink_var(bin);
                let _ = writeln!(
                    body,
                    "<text x=\"{}\" y=\"{}\" text-anchor=\"middle\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({ink_var})\" style=\"font-variant-numeric: tabular-nums\">{}</text>",
                    coord(x + cell_w / 2.0),
                    coord(y + cell_h / 2.0 + 4.0),
                    escape_xml(&fmt_sig4(value)),
                    fs = FONT_SIZE
                );
            }
        }
    }
}

/// Writes the discrete color legend (11 steps from -5..=5 stacked
/// vertically).
fn heatmap_legend(body: &mut String, width: f64, m: &Margins, plot_h: f64, legend_w: f64) {
    let legend_x = width - legend_w + 8.0;
    let swatch_h = (plot_h / 11.0).max(6.0);
    for (i, bin) in (-5..=5).rev().enumerate() {
        let y = m.top + i as f64 * swatch_h;
        let fill_var = theme::diverging_var(bin);
        let range_desc = diverging_bin_range_desc(bin);
        let _ = writeln!(
            body,
            "<rect x=\"{}\" y=\"{}\" width=\"14\" height=\"{}\" fill=\"var({fill_var})\"><title>{}</title></rect>",
            coord(legend_x),
            coord(y),
            coord(swatch_h.max(1.0)),
            escape_xml(&range_desc)
        );
        if bin == 5 || bin == 0 || bin == -5 {
            let label = if bin == 5 {
                "1"
            } else if bin == -5 {
                "-1"
            } else {
                "0"
            };
            text_muted(
                body,
                legend_x + 18.0,
                y + swatch_h / 2.0 + 3.0,
                "start",
                label,
                true,
            );
        }
    }
}

/// Builds a string describing the value range a quantization step
/// represents, for the legend's `<title>`.
fn diverging_bin_range_desc(bin: i32) -> String {
    match bin {
        0 => "0".to_string(),
        b if b > 0 => {
            let lower = (b - 1) as f64 / 5.0;
            let upper = b as f64 / 5.0;
            format!("{lower} < ρ ≤ {upper}")
        }
        b => {
            let lower = b as f64 / 5.0;
            let upper = (b + 1) as f64 / 5.0;
            format!("{lower} ≤ ρ < {upper}")
        }
    }
}

// ================================================================
// Tests
// ================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Confirms that `fill="..."` / `stroke="..."` attribute values contain
    /// no `#` (raw hex color codes are forbidden; `var(--foo)` never
    /// contains `#`).
    fn assert_no_raw_hex_in_color_attrs(svg: &str) {
        for attr in ["fill=\"", "stroke=\""] {
            let mut rest = svg;
            while let Some(pos) = rest.find(attr) {
                let after = &rest[pos + attr.len()..];
                let end = after.find('"').expect("unterminated attribute");
                let value = &after[..end];
                assert!(
                    !value.contains('#'),
                    "raw hex color found in {attr}: {value}"
                );
                rest = &after[end..];
            }
        }
    }

    /// Counts occurrences of the `<title>` element.
    fn count_titles(svg: &str) -> usize {
        svg.matches("<title>").count()
    }

    fn count(svg: &str, needle: &str) -> usize {
        svg.matches(needle).count()
    }

    // ---------------- nice_ticks ----------------

    #[test]
    fn nice_ticks_basic_range() {
        let ticks = nice_ticks(0.0, 95.0, 5);
        assert!(ticks.len() >= 2);
        assert!(ticks[0] <= 0.0);
        assert!(*ticks.last().unwrap() >= 95.0);
        for w in ticks.windows(2) {
            assert!(w[1] > w[0]);
        }
    }

    #[test]
    fn nice_ticks_negative_range() {
        let ticks = nice_ticks(-50.0, -3.0, 5);
        assert!(ticks[0] <= -50.0);
        assert!(*ticks.last().unwrap() >= -3.0);
        assert!(ticks.windows(2).all(|w| w[1] > w[0]));
    }

    #[test]
    fn nice_ticks_straddling_zero() {
        let ticks = nice_ticks(-1.5, 2.5, 5);
        assert!(ticks[0] <= -1.5);
        assert!(*ticks.last().unwrap() >= 2.5);
    }

    #[test]
    fn nice_ticks_tiny_range() {
        let ticks = nice_ticks(0.000_010, 0.000_030, 5);
        assert!(ticks[0] <= 0.000_010);
        assert!(*ticks.last().unwrap() >= 0.000_030);
        assert!(ticks.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn nice_ticks_degenerate_min_equals_max_nonzero() {
        let ticks = nice_ticks(5.0, 5.0, 5);
        assert!(ticks.len() >= 2);
        assert!(ticks.iter().all(|v| v.is_finite()));
        assert!(ticks[0] <= 5.0 && *ticks.last().unwrap() >= 5.0);
    }

    #[test]
    fn nice_ticks_degenerate_min_equals_max_zero() {
        let ticks = nice_ticks(0.0, 0.0, 5);
        assert!(ticks.len() >= 2);
        assert!(ticks.iter().all(|v| v.is_finite()));
        assert!(ticks[0] <= 0.0 && *ticks.last().unwrap() >= 0.0);
    }

    #[test]
    fn nice_ticks_integer_produces_distinct_integers() {
        let ticks = nice_ticks_integer(0.0, 59.0, 6);
        assert!(ticks.len() >= 2);
        let mut sorted = ticks.clone();
        sorted.dedup();
        assert_eq!(sorted.len(), ticks.len());
    }

    #[test]
    fn nice_ticks_integer_degenerate() {
        // Even in the degenerate case (min == max), this must not panic
        // and must return an ascending integer sequence containing the
        // value.
        let ticks = nice_ticks_integer(3.0, 3.0, 6);
        assert!(!ticks.is_empty());
        assert!(ticks.windows(2).all(|w| w[1] > w[0]));
        assert!(ticks[0] <= 3 && *ticks.last().unwrap() >= 3);
    }

    // ---------------- escaping ----------------

    #[test]
    fn escape_xml_handles_all_special_chars() {
        assert_eq!(
            escape_xml("<script>&\"'</script>"),
            "&lt;script&gt;&amp;&quot;&apos;&lt;/script&gt;"
        );
    }

    #[test]
    fn hbar_chart_escapes_malicious_label() {
        let items = vec![HBarItem {
            label: "<script>alert(1)</script>".to_string(),
            value: 1.0,
        }];
        let svg = hbar_chart(&items, 400.0);
        assert!(!svg.contains("<script>alert"));
        assert!(svg.contains("&lt;script&gt;"));
    }

    // ---------------- fmt_sig4 ----------------

    #[test]
    fn fmt_sig4_basic_cases() {
        assert_eq!(fmt_sig4(0.0), "0");
        assert_eq!(fmt_sig4(1234.0), "1234");
        assert_eq!(fmt_sig4(1234.5678), "1235");
        assert_eq!(fmt_sig4(0.00012345), "0.0001234");
        assert_eq!(fmt_sig4(-12.3456), "-12.35");
        assert_eq!(fmt_sig4(0.1), "0.1");
        assert_eq!(fmt_sig4(100.0), "100");
    }

    // ---------------- line_chart ----------------

    #[test]
    fn line_chart_mark_and_title_counts() {
        let points: Vec<LinePoint> = (0..10)
            .map(|i| LinePoint {
                trial_number: i,
                value: (i as f64).sin(),
            })
            .collect();
        let improvement = vec![0usize, 3, 7];
        let svg = line_chart(&points, &improvement, 400.0, 200.0);

        // improvement marks (3) + final point marker (idx 9 not in improvement) = 4 circles.
        assert_eq!(count(&svg, "<circle"), 4);
        assert_eq!(count_titles(&svg), 4);
        assert_no_raw_hex_in_color_attrs(&svg);
    }

    #[test]
    fn line_chart_final_point_already_improvement_no_duplicate_marker() {
        let points: Vec<LinePoint> = (0..5)
            .map(|i| LinePoint {
                trial_number: i,
                value: i as f64,
            })
            .collect();
        let improvement = vec![0usize, 4];
        let svg = line_chart(&points, &improvement, 300.0, 150.0);
        assert_eq!(count(&svg, "<circle"), 2);
        assert_eq!(count_titles(&svg), 2);
    }

    #[test]
    fn line_chart_empty_points_no_panic() {
        let svg = line_chart(&[], &[], 300.0, 150.0);
        assert!(svg.contains("no data"));
    }

    // ---------------- scatter_chart ----------------

    #[test]
    fn scatter_chart_mark_and_title_counts() {
        let background: Vec<ScatterPoint> = (0..20)
            .map(|i| ScatterPoint {
                trial_number: i,
                x: i as f64,
                y: (20 - i) as f64,
                feasible: true,
            })
            .collect();
        let front: Vec<ScatterPoint> = (0..5)
            .map(|i| ScatterPoint {
                trial_number: i,
                x: i as f64 * 2.0,
                y: (5 - i) as f64,
                feasible: true,
            })
            .collect();
        let svg = scatter_chart(&background, &front, "obj1", "obj2", 400.0, 300.0);

        // data marks + 2 legend markers (legend markers get no <title>).
        assert_eq!(count(&svg, "<circle"), background.len() + front.len() + 2);
        assert_eq!(count_titles(&svg), background.len() + front.len());
        assert!(svg.contains("<path"));
        // legend is required because there are two series (front / dominated).
        assert!(svg.contains("Pareto front"));
        assert!(svg.contains("dominated"));
        assert_no_raw_hex_in_color_attrs(&svg);
    }

    #[test]
    fn scatter_chart_no_legend_when_single_series() {
        // background only (single series) means no legend (shared rule).
        let background: Vec<ScatterPoint> = (0..5)
            .map(|i| ScatterPoint {
                trial_number: i,
                x: i as f64,
                y: i as f64,
                feasible: true,
            })
            .collect();
        let svg = scatter_chart(&background, &[], "x", "y", 300.0, 200.0);
        assert!(!svg.contains("Pareto front"));
        assert_eq!(count(&svg, "<circle"), background.len());
    }

    #[test]
    fn scatter_chart_single_front_point_no_staircase_path() {
        let background = vec![ScatterPoint {
            trial_number: 0,
            x: 1.0,
            y: 1.0,
            feasible: true,
        }];
        let front = vec![ScatterPoint {
            trial_number: 0,
            x: 1.0,
            y: 1.0,
            feasible: true,
        }];
        let svg = scatter_chart(&background, &front, "x", "y", 300.0, 200.0);
        assert!(!svg.contains("<path"));
    }

    #[test]
    fn scatter_chart_marks_infeasible_in_tooltip() {
        // Points with feasible=false get [infeasible] appended to their
        // tooltip. Feasible points do not get it.
        let background = vec![
            ScatterPoint {
                trial_number: 0,
                x: 1.0,
                y: 2.0,
                feasible: false,
            },
            ScatterPoint {
                trial_number: 1,
                x: 2.0,
                y: 1.0,
                feasible: true,
            },
        ];
        let svg = scatter_chart(&background, &[], "x", "y", 300.0, 200.0);
        assert_eq!(count(&svg, "[infeasible]"), 1);
        assert!(svg.contains("trial #0 (1, 2) [infeasible]"));
        assert!(svg.contains("trial #1 (2, 1)</title>"));
    }

    // ---------------- hbar_chart ----------------

    #[test]
    fn hbar_chart_mark_and_title_counts() {
        let items = vec![
            HBarItem {
                label: "alpha".to_string(),
                value: 0.8,
            },
            HBarItem {
                label: "a_very_long_parameter_name_that_exceeds_limit".to_string(),
                value: 0.5,
            },
            HBarItem {
                label: "gamma".to_string(),
                value: 0.2,
            },
        ];
        let svg = hbar_chart(&items, 400.0);
        assert_eq!(count(&svg, "<rect"), items.len());
        // rect titles + label <text> titles (both counted) = 2 * items.len()
        assert_eq!(count_titles(&svg), items.len() * 2);
        assert_no_raw_hex_in_color_attrs(&svg);
    }

    #[test]
    fn hbar_chart_truncates_long_label_with_ellipsis() {
        let long_name = "a_very_long_parameter_name_that_exceeds_limit";
        let items = vec![HBarItem {
            label: long_name.to_string(),
            value: 1.0,
        }];
        let svg = hbar_chart(&items, 400.0);
        assert!(svg.contains('…'));
        // full label preserved in title
        assert!(svg.contains(long_name));
    }

    // ---------------- histogram ----------------

    #[test]
    fn histogram_mark_and_title_counts() {
        let bins: Vec<HistBin> = (0..20)
            .map(|i| HistBin {
                lower: i as f64,
                upper: (i + 1) as f64,
                count: (i % 7) as u64,
            })
            .collect();
        let svg = histogram(&bins, 500.0, 200.0);
        assert_eq!(count(&svg, "<rect"), bins.len());
        assert_eq!(count_titles(&svg), bins.len());
        assert_no_raw_hex_in_color_attrs(&svg);
    }

    // ---------------- heatmap ----------------

    #[test]
    fn heatmap_mark_and_title_counts() {
        let matrix = vec![vec![-1.0, -0.51, -0.5, 0.0], vec![0.5, 0.51, 1.0, 0.2]];
        let row_labels = vec!["p1".to_string(), "p2".to_string()];
        let col_labels = vec![
            "o1".to_string(),
            "o2".to_string(),
            "o3".to_string(),
            "o4".to_string(),
        ];
        let svg = heatmap(&matrix, &row_labels, &col_labels, 500.0);

        let cell_count = 2 * 4;
        assert_eq!(count(&svg, "<rect"), cell_count + 11); // cells + legend swatches
                                                           // title count = cell titles + legend titles (11)
        assert_eq!(count_titles(&svg), cell_count + 11);
        assert_no_raw_hex_in_color_attrs(&svg);
    }

    #[test]
    fn heatmap_quantization_boundaries() {
        // Confirm that at the boundary values -1, -0.51, -0.5, 0, 0.5,
        // 0.51, 1, the quantization step and label-visibility both match
        // the expected theoretical values.
        let cases = [
            (-1.0, -5, true),
            (-0.51, -3, true),
            (-0.5, -3, false),
            (0.0, 0, false),
            (0.5, 3, false),
            (0.51, 3, true),
            (1.0, 5, true),
        ];
        for (v, expected_bin, expected_label) in cases {
            assert_eq!(theme::diverging_bin(v), expected_bin, "bin for {v}");
            assert_eq!(
                theme::diverging_show_label(v),
                expected_label,
                "label for {v}"
            );
        }
    }

    #[test]
    fn heatmap_empty_matrix_no_panic() {
        let svg = heatmap(&[], &[], &[], 400.0);
        assert!(svg.contains("no data"));
    }

    #[test]
    fn heatmap_truncates_long_labels_with_title() {
        let long_row = "an_extremely_long_row_parameter_name_here";
        let long_col = "an_extremely_long_objective_name";
        let matrix = vec![vec![0.3]];
        let svg = heatmap(
            &matrix,
            &[long_row.to_string()],
            &[long_col.to_string()],
            500.0,
        );
        // The display is truncated, and the full label is preserved in
        // <title>.
        assert!(svg.contains('…'));
        assert!(svg.contains(long_row));
        assert!(svg.contains(long_col));
    }

    #[test]
    fn truncate_label_respects_max_chars() {
        let s = "0123456789012345678901234567"; // 29 chars
        let t = truncate_label(s, 24);
        assert_eq!(t.chars().count(), 24);
        assert!(t.ends_with('…'));
        assert_eq!(truncate_label("short", 24), "short");
    }
}
