//! 依存クレートのライセンス情報。
//!
//! 実体は `build.rs` が `cargo metadata` から収集し、`OUT_DIR/licenses.rs` に
//! `pub static LICENSES: &[LicenseEntry]` として生成する。ここではその配列が
//! 参照する型を定義し、生成ファイルを `include!` で取り込む。

/// 1 つの依存クレートのライセンス情報。
pub struct LicenseEntry {
    /// クレート名。
    pub name: &'static str,
    /// バージョン（例: "1.2.3"）。
    pub version: &'static str,
    /// SPDX ライセンス式（例: "MIT OR Apache-2.0"）。不明な場合は空文字。
    pub license: &'static str,
    /// リポジトリ URL。未設定なら空文字。
    pub repository: &'static str,
    /// LICENSE / COPYING / NOTICE 等の全文（複数ファイルは見出し付きで連結）。
    /// クレートが同梱していない場合は空文字。
    pub text: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/licenses.rs"));

#[cfg(test)]
mod tests {
    use super::LICENSES;

    #[test]
    fn licenses_are_collected() {
        // build.rs が依存クレートを 1 件以上収集できていること。
        assert!(
            !LICENSES.is_empty(),
            "no license entries were generated by build.rs"
        );
    }

    #[test]
    fn entries_have_name_and_version() {
        for e in LICENSES {
            assert!(!e.name.is_empty(), "entry with empty name");
            assert!(!e.version.is_empty(), "entry {} has empty version", e.name);
        }
    }
}
