//! Shared drawing / formatting / tick-generation helpers used by the
//! `report::svg` chart submodules.

use std::fmt::Write as _;

use crate::report::theme;

/// Font size shared by all text (in viewBox units).
///
/// Without an explicit value on the SVG side, text renders at the page's
/// default size (around 16px), which breaks character-width-based margin
/// calculations, so this value is always emitted as the `font-size`
/// attribute (the font **family** stays `inherit` and follows the page).
pub(super) const FONT_SIZE: f64 = 12.0;

/// Estimated width per character used for margin calculations (px, at
/// `FONT_SIZE`).
///
/// Set a bit wider than the average alphanumeric character width for
/// system-ui-style fonts, as a safety margin so truncated labels don't
/// overflow the margin.
pub(super) const CHAR_W: f64 = 7.0;

/// Padding around the plot area. Determined by whether labels are present.
pub(super) struct Margins {
    pub(super) top: f64,
    pub(super) right: f64,
    pub(super) bottom: f64,
    pub(super) left: f64,
}

/// Escapes a string so it is safe as XML text content / attribute value.
///
/// The order of operations matters: `&` must be processed first, otherwise
/// the entity references generated by later substitutions (e.g. `&amp;`)
/// would get double-escaped.
///
/// The escaped set (`& < > " '`) is also safe for HTML text nodes /
/// double-quoted attribute values, and the `html` renderer shares this
/// implementation (`&apos;` is a valid entity reference in HTML5, so this
/// isn't a discrepancy).
pub(crate) fn escape_xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

/// Numeric formatter for SVG coordinates/sizes (fixed to 2 decimal places).
///
/// Serves a different purpose than the formatter used to display data
/// values ([`fmt_sig4`]) — this one is for drawing coordinates and has no
/// notion of significant digits.
pub(super) fn coord(v: f64) -> String {
    format!("{v:.2}")
}

/// 4-significant-digit formatter for displaying data values (equivalent to
/// `%.4g`).
///
/// This intentionally duplicates the shared formatter used elsewhere in
/// the report (presumably `crate::report::format_number`), in order to
/// keep `report::svg` loosely coupled from other modules (see the design
/// doc).
pub(super) fn fmt_sig4(v: f64) -> String {
    if v == 0.0 {
        return "0".to_string();
    }
    if v.is_nan() {
        return "NaN".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 {
            "inf".to_string()
        } else {
            "-inf".to_string()
        };
    }

    let sign = if v.is_sign_negative() { "-" } else { "" };
    let av = v.abs();
    let exponent = av.log10().floor() as i32;

    if !(-4..4).contains(&exponent) {
        // Exponential notation: round the mantissa to 4 significant digits
        // (3 decimal places).
        let mantissa = av / 10f64.powi(exponent);
        let mantissa_str = trim_trailing_zeros(&format!("{mantissa:.3}"));
        let exp_sign = if exponent >= 0 { "+" } else { "-" };
        format!("{sign}{mantissa_str}e{exp_sign}{}", exponent.abs())
    } else {
        let decimals = (3 - exponent).max(0) as usize;
        let s = trim_trailing_zeros(&format!("{av:.decimals$}"));
        format!("{sign}{s}")
    }
}

/// Strips trailing zeros after the decimal point (and any now-unneeded
/// decimal point).
fn trim_trailing_zeros(s: &str) -> String {
    if !s.contains('.') {
        return s.to_string();
    }
    let trimmed = s.trim_end_matches('0');
    trimmed.trim_end_matches('.').to_string()
}

/// Computes a nice number (1 / 2 / 5 × 10^n).
///
/// If `round` is true, returns the nearest nice number; if false, returns
/// the smallest nice number that is `>= range` (used to determine tick
/// spacing).
fn nice_num(range: f64, round: bool) -> f64 {
    if range <= 0.0 {
        return 1.0;
    }
    let exponent = range.log10().floor();
    let fraction = range / 10f64.powf(exponent);
    let nice_fraction = if round {
        if fraction < 1.5 {
            1.0
        } else if fraction < 3.0 {
            2.0
        } else if fraction < 7.0 {
            5.0
        } else {
            10.0
        }
    } else if fraction <= 1.0 {
        1.0
    } else if fraction <= 2.0 {
        2.0
    } else if fraction <= 5.0 {
        5.0
    } else {
        10.0
    };
    nice_fraction * 10f64.powf(exponent)
}

/// Computes tick positions using the nice-number algorithm (Heckbert's
/// method).
///
/// In the degenerate case `min == max`, an artificial width is applied
/// around the value before the usual algorithm runs (`[-1, 1]` if
/// `min == max == 0.0`, otherwise half the absolute value as the width),
/// so single-point data or constant series never panic or produce NaN and
/// always return at least two ticks.
pub(super) fn nice_ticks(min: f64, max: f64, target_count: usize) -> Vec<f64> {
    let (min, max) = if min > max { (max, min) } else { (min, max) };
    let (min, max) = if (max - min).abs() < f64::EPSILON {
        let pad = if min == 0.0 { 1.0 } else { min.abs() * 0.5 };
        (min - pad, max + pad)
    } else {
        (min, max)
    };

    let target = target_count.max(2);
    let range = nice_num(max - min, false);
    let spacing = nice_num(range / (target - 1) as f64, true);
    let nice_min = (min / spacing).floor() * spacing;
    let nice_max = (max / spacing).ceil() * spacing;

    let n = ((nice_max - nice_min) / spacing).round() as i64;
    (0..=n).map(|i| nice_min + spacing * i as f64).collect()
}

/// Computes integer ticks (for the trial-number X axis).
///
/// Rounds the [`nice_ticks`] result and removes duplicates; if fewer than
/// two ticks remain, falls back to the actual min/max values (as
/// integers).
pub(super) fn nice_ticks_integer(min: f64, max: f64, target_count: usize) -> Vec<i64> {
    let mut ticks: Vec<i64> = nice_ticks(min, max, target_count)
        .into_iter()
        .map(|t| t.round() as i64)
        .collect();
    ticks.dedup();
    if ticks.len() >= 2 {
        return ticks;
    }
    let lo = min.floor() as i64;
    let hi = max.ceil() as i64;
    if lo == hi {
        vec![lo]
    } else {
        vec![lo, hi]
    }
}

/// Writes a hairline grid line (`<line>`) to `body`.
pub(super) fn hairline(body: &mut String, x1: f64, y1: f64, x2: f64, y2: f64) {
    let _ = writeln!(
        body,
        "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"var({grid})\" stroke-width=\"1\" />",
        coord(x1),
        coord(y1),
        coord(x2),
        coord(y2),
        grid = theme::VAR_GRID
    );
}

/// Writes an axis line (`<line>`) to `body`.
pub(super) fn axis_line(body: &mut String, x1: f64, y1: f64, x2: f64, y2: f64) {
    let _ = writeln!(
        body,
        "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"var({axis})\" stroke-width=\"1\" />",
        coord(x1),
        coord(y1),
        coord(x2),
        coord(y2),
        axis = theme::VAR_AXIS
    );
}

/// Writes muted-ink text (for axis ticks / category labels) to `body`.
pub(super) fn text_muted(
    body: &mut String,
    x: f64,
    y: f64,
    anchor: &str,
    content: &str,
    numeric: bool,
) {
    let style = if numeric {
        " style=\"font-variant-numeric: tabular-nums\""
    } else {
        ""
    };
    let _ = writeln!(
        body,
        "<text x=\"{}\" y=\"{}\" text-anchor=\"{anchor}\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({muted})\"{style}>{}</text>",
        coord(x),
        coord(y),
        escape_xml(content),
        fs = FONT_SIZE,
        muted = theme::VAR_INK_MUTED
    );
}

/// Writes a secondary-ink direct data label (final value, bar-end value,
/// etc.) to `body`.
pub(super) fn text_secondary(body: &mut String, x: f64, y: f64, anchor: &str, content: &str) {
    let _ = writeln!(
        body,
        "<text x=\"{}\" y=\"{}\" text-anchor=\"{anchor}\" font-family=\"inherit\" font-size=\"{fs}\" fill=\"var({secondary})\" style=\"font-variant-numeric: tabular-nums\">{}</text>",
        coord(x),
        coord(y),
        escape_xml(content),
        fs = FONT_SIZE,
        secondary = theme::VAR_INK_SECONDARY
    );
}

/// Wraps the chart body in the SVG root element (viewBox-based, responsive).
pub(super) fn svg_wrap(width: f64, height: f64, body: &str) -> String {
    format!(
        "<svg viewBox=\"0 0 {w} {h}\" width=\"100%\" height=\"auto\" preserveAspectRatio=\"xMinYMin meet\" xmlns=\"http://www.w3.org/2000/svg\">\n{body}</svg>\n",
        w = coord(width),
        h = coord(height)
    )
}

/// Placeholder shown when the data is empty.
pub(super) fn empty_message(width: f64, height: f64) -> String {
    let mut body = String::new();
    text_muted(
        &mut body,
        width / 2.0,
        height / 2.0,
        "middle",
        "no data",
        false,
    );
    svg_wrap(width, height, &body)
}

/// Truncates a category label to the given character count, appending `…`
/// if it was too long.
pub(super) fn truncate_label(s: &str, max_chars: usize) -> String {
    let chars: Vec<char> = s.chars().collect();
    if chars.len() <= max_chars {
        s.to_string()
    } else {
        let head: String = chars[..max_chars.saturating_sub(1)].iter().collect();
        format!("{head}…")
    }
}
